services:
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
    - "127.0.0.1:8123:8123"
    - "127.0.0.1:9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true
    volumes:
    - ./data:/var/lib/clickhouse
    - ./log:/var/log/clickhouse-server
    env_file: ../.env
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
    - clickhouse

networks:
  clickhouse:
    name: clickhouse
