apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  uid: main-prometheus
  isDefault: true
  access: proxy
  editable: false
- name: Loki
  type: loki
  url: http://loki:3100
  uid: main-loki
  editable: false
