services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "443:443/udp"
    volumes:
    - conf:/etc/nginx/conf.d
    - vhost:/etc/nginx/vhost.d
    - html:/usr/share/nginx/html
    - dhparam:/etc/nginx/dhparam
    - certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    healthcheck:
      test: ["CMD", "nc", "-vz", "-w1", "localhost", "80"]
      interval: 10s
      timeout: 1s
      retries: 30
    environment:
      ENABLE_HTTP2: true
      ENABLE_IPV6: true
      ENABLE_HTTP3: false
    networks:
    - webserver

  mkcert:
    image: aegypius/mkcert-for-nginx-proxy
    restart: always
    volumes_from:
    - nginx-proxy
    volumes:
    - certs:/app/certs:rw
    - ~/.mozilla/firefox:/root/.mozilla/firefox:rw
    - ~/.pki/nssdb:/root/.pki/nssdb:rw
    - ${CA_STORE:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
    - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    networks:
    - webserver

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  webserver:
    name: webserver
