services:
  spectator-server:
    image: ghcr.io/opensource-deadlock-tools/devlock/spectator/server:latest
    build: .
    restart: always
    env_file: ../../.env
    networks:
    - rabbitmq

networks:
  rabbitmq:
    external: true
