services:
  grafana:
    image: grafana/grafana-enterprise
    restart: always
    env_file: ../.env
    user: "1000"
    volumes:
    - grafana-data:/var/lib/grafana
    - ./grafana/dashboards:/dashboards
    - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    ports:
    - "3000:3000"
    environment:
      VIRTUAL_HOST: grafana.devlock.net
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: grafana.devlock.net
      GF_SERVER_DOMAIN: grafana.devlock.net
      GF_SERVER_ROOT_URL: https://grafana.devlock.net
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email offline_access"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.devlock.net/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.devlock.net/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.devlock.net/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.devlock.net/application/o/grafana/end-session/"
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin'\
        \ || contains(groups, 'Grafana Editors') && 'Editor' || contains(groups, 'Grafana Viewers')\
        \ && 'Viewer' || 'None'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
    - monitoring
    - webserver

  node-exporter:
    image: prom/node-exporter
    restart: always
    volumes:
    - /:/host:ro,rslave
    expose:
    - 9100
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
    - monitoring

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
    - monitoring

  watchtower:
    image: containrrr/watchtower
    restart: always
    env_file: ../.env
    environment:
      DOCKER_CONFIG: /config
      WATCHTOWER_WARN_ON_HEAD_FAILURE: never
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --rolling-restart

  autoheal:
    image: willfarrell/autoheal
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env_file: ../.env
    environment:
      AUTOHEAL_CONTAINER_LABEL: all

volumes:
  grafana-data:

networks:
  monitoring:
    name: monitoring
  webserver:
    external: true
