global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ["localhost:9090"]
- job_name: node
  static_configs:
  - targets: ['node-exporter:9100']
- job_name: api
  static_configs:
  - targets: ['api:8080']
- job_name: Clickhouse
  static_configs:
  - targets: ['clickhouse:9363']
- job_name: RabbitMQ
  static_configs:
  - targets: ['rabbitmq:15692']
- job_name: Authentik
  static_configs:
  - targets: ['authentik:9300']
- job_name: watchtower
  metrics_path: /v1/metrics
  bearer_token: watchtower-api-token
  static_configs:
  - targets: ['watchtower:8080']
