global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ["localhost:9090"]
- job_name: node
  static_configs:
  - targets: ['node-exporter:9100']
- job_name: clickhouse
  static_configs:
  - targets: ['clickhouse-exporter:9116']
- job_name: RabbitMQ
  static_configs:
  - targets: ['rabbitmq:15692']
- job_name: Authentik
  static_configs:
  - targets: ['authentik:9300']
