services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    ports:
    - "5672:5672" # RabbitMQ default port
    - "15672:15672" # RabbitMQ management UI
    volumes:
    - ./data:/var/lib/rabbitmq
    - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    env_file: ../.env
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - rabbitmq
    - monitoring

networks:
  rabbitmq:
    name: rabbitmq
  monitoring:
    external: true
