services:
  active-matches-scraper:
    image: ghcr.io/opensource-deadlock-tools/devlock/active-matches-scraper
    build: .
    restart: always
    env_file: ../.env
    environment:
      CACHE_FOLDER: /tmp
      MATCHES_PER_FILE: 10000
    volumes:
    - tmp:/tmp
    networks:
    - rabbitmq

volumes:
  tmp:

networks:
  rabbitmq:
    external: true
