services:
  user-ingest:
    image: ghcr.io/opensource-deadlock-tools/devlock/user-ingest
    build: .
    restart: always
    env_file: ../.env
    environment:
      VIRTUAL_HOST: ingest.devlock.net
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ingest.devlock.net
    stop_grace_period: 2m # Allow all in-flight uploads to complete
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
    - rabbitmq
    - webserver
    - clickhouse

networks:
  rabbitmq:
    external: true
  webserver:
    external: true
  clickhouse:
    external: true
