// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name
// @generated from protobuf file "citadel_usercmd.proto" (syntax proto2)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { CMsgQAngle } from "./networkbasetypes.js";
import { CMsgVector } from "./networkbasetypes.js";
import { CBaseUserCmdPB } from "./usercmd.js";
/**
 * @generated from protobuf message CCitadelUserCmdPB
 */
export interface CCitadelUserCmdPB {
  /**
   * @generated from protobuf field: optional CBaseUserCmdPB base = 1;
   */
  base?: CBaseUserCmdPB;
  /**
   * @generated from protobuf field: optional CMsgVector vec_camera_position = 2;
   */
  vec_camera_position?: CMsgVector;
  /**
   * @generated from protobuf field: optional CMsgQAngle ang_camera_angles = 3;
   */
  ang_camera_angles?: CMsgQAngle;
  /**
   * @generated from protobuf field: optional int32 execute_ability_indices = 4;
   */
  execute_ability_indices?: number;
  /**
   * @generated from protobuf field: optional bool in_shop = 5;
   */
  in_shop?: boolean;
  /**
   * @generated from protobuf field: optional float camera_roaming_speed = 6;
   */
  camera_roaming_speed?: number;
  /**
   * @generated from protobuf field: optional bool using_free_cursor = 8;
   */
  using_free_cursor?: boolean;
  /**
   * @generated from protobuf field: optional int32 enemy_hero_aimed_at = 10;
   */
  enemy_hero_aimed_at?: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class CCitadelUserCmdPB$Type extends MessageType<CCitadelUserCmdPB> {
  constructor() {
    super("CCitadelUserCmdPB", [
      { no: 1, name: "base", kind: "message", T: () => CBaseUserCmdPB },
      {
        no: 2,
        name: "vec_camera_position",
        kind: "message",
        localName: "vec_camera_position",
        T: () => CMsgVector,
      },
      {
        no: 3,
        name: "ang_camera_angles",
        kind: "message",
        localName: "ang_camera_angles",
        T: () => CMsgQAngle,
      },
      {
        no: 4,
        name: "execute_ability_indices",
        kind: "scalar",
        localName: "execute_ability_indices",
        opt: true,
        T: 5 /*ScalarType.INT32*/,
      },
      {
        no: 5,
        name: "in_shop",
        kind: "scalar",
        localName: "in_shop",
        opt: true,
        T: 8 /*ScalarType.BOOL*/,
      },
      {
        no: 6,
        name: "camera_roaming_speed",
        kind: "scalar",
        localName: "camera_roaming_speed",
        opt: true,
        T: 2 /*ScalarType.FLOAT*/,
      },
      {
        no: 8,
        name: "using_free_cursor",
        kind: "scalar",
        localName: "using_free_cursor",
        opt: true,
        T: 8 /*ScalarType.BOOL*/,
      },
      {
        no: 10,
        name: "enemy_hero_aimed_at",
        kind: "scalar",
        localName: "enemy_hero_aimed_at",
        opt: true,
        T: 5 /*ScalarType.INT32*/,
      },
    ]);
  }
  create(value?: PartialMessage<CCitadelUserCmdPB>): CCitadelUserCmdPB {
    const message = globalThis.Object.create(this.messagePrototype!);
    if (value !== undefined) reflectionMergePartial<CCitadelUserCmdPB>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: CCitadelUserCmdPB,
  ): CCitadelUserCmdPB {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* optional CBaseUserCmdPB base */ 1:
          message.base = CBaseUserCmdPB.internalBinaryRead(reader, reader.uint32(), options, message.base);
          break;
        case /* optional CMsgVector vec_camera_position */ 2:
          message.vec_camera_position = CMsgVector.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.vec_camera_position,
          );
          break;
        case /* optional CMsgQAngle ang_camera_angles */ 3:
          message.ang_camera_angles = CMsgQAngle.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.ang_camera_angles,
          );
          break;
        case /* optional int32 execute_ability_indices */ 4:
          message.execute_ability_indices = reader.int32();
          break;
        case /* optional bool in_shop */ 5:
          message.in_shop = reader.bool();
          break;
        case /* optional float camera_roaming_speed */ 6:
          message.camera_roaming_speed = reader.float();
          break;
        case /* optional bool using_free_cursor */ 8:
          message.using_free_cursor = reader.bool();
          break;
        case /* optional int32 enemy_hero_aimed_at */ 10:
          message.enemy_hero_aimed_at = reader.int32();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          let d = reader.skip(wireType);
          if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
      }
    }
    return message;
  }
  internalBinaryWrite(message: CCitadelUserCmdPB, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
    /* optional CBaseUserCmdPB base = 1; */
    if (message.base)
      CBaseUserCmdPB.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
    /* optional CMsgVector vec_camera_position = 2; */
    if (message.vec_camera_position)
      CMsgVector.internalBinaryWrite(
        message.vec_camera_position,
        writer.tag(2, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* optional CMsgQAngle ang_camera_angles = 3; */
    if (message.ang_camera_angles)
      CMsgQAngle.internalBinaryWrite(
        message.ang_camera_angles,
        writer.tag(3, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* optional int32 execute_ability_indices = 4; */
    if (message.execute_ability_indices !== undefined)
      writer.tag(4, WireType.Varint).int32(message.execute_ability_indices);
    /* optional bool in_shop = 5; */
    if (message.in_shop !== undefined) writer.tag(5, WireType.Varint).bool(message.in_shop);
    /* optional float camera_roaming_speed = 6; */
    if (message.camera_roaming_speed !== undefined) writer.tag(6, WireType.Bit32).float(message.camera_roaming_speed);
    /* optional bool using_free_cursor = 8; */
    if (message.using_free_cursor !== undefined) writer.tag(8, WireType.Varint).bool(message.using_free_cursor);
    /* optional int32 enemy_hero_aimed_at = 10; */
    if (message.enemy_hero_aimed_at !== undefined) writer.tag(10, WireType.Varint).int32(message.enemy_hero_aimed_at);
    let u = options.writeUnknownFields;
    if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message CCitadelUserCmdPB
 */
export const CCitadelUserCmdPB = new CCitadelUserCmdPB$Type();
